### ISSUE TITLE
Allow grading of OOB assignment

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#66]
Two issues here:

1) new gems required #58
2) support files required #60

We can hack this short term by adding gems and support files directly to grader

**Comment by tansaku** [comment]
addressed in this pull request https://github.com/saasbook/rag/pull/65

**Comment by zhangaaron** [comment]
Hey, this seems good to me. Not too familiar with OoB homework, so why is this a hack?

**Comment by tansaku** [comment]
@zhangaaron it's a hack in as much as:

1) we're adding gems to the grader that the grader doesn't need per se
2) we're adding supporting files specifically for OoB to the grader, since the current OoB spec can't access them in the place that they are imported to.

The associated pull request adds a load of stuff to the grader to make OoB work.  If someone changes the OoB assignment files or gems then those changes will not get transferred over to, or be used by, the grader.  It locks the current OoB into the grader preventing encapsulation of the assignment from the grader.

It's not very DRY.  In the ideal world all these things (new gems, supporting files etc.) would get pulled into a usable location via the specification of ``git@github.com:saasbook/hw-oracle-of-bacon-ci.git`` the repo in the grader json payload:

```
		{"assignment_name": "assignment1.5",
		"assignment_spec_uri": "git@github.com:saasbook/hw-oracle-of-bacon-ci.git",
		"autograder_type": "RspecGrader",
		"due_dates": {"2016-01-23": 1.0, "2016-01-30": 0.75}      }
```

It would make sense if the Gemfile in https://github.com/saasbook/hw-oracle-of-bacon-ci was used to ensure that the grader had access to the right gems, and that the xml files such as https://github.com/saasbook/hw-oracle-of-bacon-ci/blob/master/autograder/graph_example.xml were be pulled into a location that the imported spec could access.  That's an issue of how the file paths are encoded ...

I've opened other issues for that: #58 and #60
