### ISSUE TITLE
HW4 causing the grader to crash

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#67]
During the MOOC of fall 2015 HW4 submissions appeared to cause the grader to crash hard such that it required restarting.

It would be good to address this before the current round of SPOCs get to that assignment.

It seems like we would need a load testing harness to simulate the conditions that caused the problem

**Comment by tansaku** [comment]
@zhangaaron the Berkeley class is coming up on this assignment right?  Any thoughts on the appropriate way to load test the grader to try and expose the error?

My thought in the first instance is to have a testing script that can be run on the deployed staging grader that can simulate a repeated incoming request from edX.

Danger there is that we miss some part of the XQueue submission ... wondering if we need to set up our own XQueues to test this properly ...

**Comment by zhangaaron** [comment]
Yes, I believe that will be our next homework. Was the problem ever resolved? The problem is not a hard crash but that the grader did not time out properly while grading HW4 leading to spinning forever. I think the requests can be simulated through the XQueue interface without too much worry. We could use some recorded responses and play them over.

**Comment by tansaku** [comment]
hi @zhangaaron - no we never resolved the problem.  When will your students start submitting assignments?  Do you have any time to work on investigating this?

**Comment by tansaku** [comment]
I'm going to take a start on this.  I guess a simple first pass is to get on the staging grader and play a sequence of HW4's over and over using the cucumber as a test harness

**Comment by tansaku** [comment]
So I've put the following in the staging grader in order to see if we can replicate the failure somehow:

```
while true; do bundle exec cucumber features/autograder_xqueue_stubbed.feature:44; done
```

now this does not simulate exactly repeatedly hitting the same grader, since I assume things get torn down and setup each time with the test, and we are not completely simulating the incoming network request, and it's only testing against a single passing assignement.

To really investigate this properly I guess we'd need to have our own edX queue endpoint that had a large number of homework submissions on it.  Ideally we'd somehow take the log of real submissions from a real students and play them back using the queue ...

sensibly this would be on a separate grader rather than staging which we might in a hurry to test fixes ready for deploy ...

**Comment by tansaku** [comment]
The cucumber loop is taking about 25 seconds per pass, and I'll leave it running for a bit to see what happens ... completed about 20 passes without instance so far ...

**Comment by tansaku** [comment]
I'm looking at getting an xqueue set up, looks like that would work best on a linux box - maybe I could put that on an EC2 box ... 

https://github.com/edx/xqueue/blob/master/install_xqueue.sh

**Comment by tansaku** [comment]
hmm, would it be faster to spin up a little sinatra server that would just continually serve up json in the right format for a homework submission ...

**Comment by tansaku** [comment]
however, if the problem occurs from a particular type of submission rather than due to a heavy load per se, the key thing is to analyze the particular submissions that cause a problem ...

to that end I've set up an element in the test components of the part 1 of the mooc to hit the staging grader and am going to try hitting it with some different versions of the HWs I have.

I wonder if there is some way to work out from the submission logs in the main grader to reconstruct which assignments cause the freeze ...?

**Comment by tansaku** [comment]
hmm, so looking at the time that Aaron re-started the grader, it looks like the last incoming submission before things hung was: 

```
I, [2016-02-29T11:05:45.691443 #16909]  INFO -- : XQueue adapter received submission. Student e09b7438ff91c5ba62c200112c01e479 assignment assignment4
D, [2016-02-29T11:05:45.728780 #16909] DEBUG -- : Start subprocess to run student code.
D, [2016-02-29T11:05:51.741252 #20089] DEBUG -- : setup: 5.881039381027222s
```

or possibly

```
I, [2016-02-29T16:18:47.492028 #22772]  INFO -- : XQueue adapter received submission. Student e09b7438ff91c5ba62c200112c01e479 assignment assignment4
D, [2016-02-29T16:18:47.545161 #22772] DEBUG -- : Start subprocess to run student code.
D, [2016-02-29T16:18:53.631871 #22873] DEBUG -- : setup: 5.991001129150391s
```

both of which point to assignment4 submissions

**Comment by tansaku** [comment]
so taking that last student it seems that I can see their set of submissions like so:

```
ubuntu@ip-10-182-65-242:~/rag/submissions/e09b7438ff91c5ba62c200112c01e479$ ls
assignment0-ruby-intro  assignment1-sinatra  assignment2-rails-intro  assignment3  assignment4
ubuntu@ip-10-182-65-242:~/rag/submissions/e09b7438ff91c5ba62c200112c01e479$ cd assignment4
ubuntu@ip-10-182-65-242:~/rag/submissions/e09b7438ff91c5ba62c200112c01e479/assignment4$ ls
2016-02-29-11-05-45  2016-02-29-16-17-54  2016-02-29-16-18-47  2016-03-01-01-04-55  2016-03-01-07-50-11  2016-03-01-07-56-26  2016-03-01-15-23-52  2016-03-01-17-26-03
2016-02-29-16-17-27  2016-02-29-16-18-20  2016-03-01-01-03-18  2016-03-01-01-30-20  2016-03-01-07-56-00  2016-03-01-08-34-49  2016-03-01-15-25-50  2016-03-01-17-27-00
```

**Comment by tansaku** [comment]
so I have pulled that submission off the production grader and submitted that to the staging grader ... and it looks like it is stuck ... now perhaps I can make a failing test case out of that ...
