### ISSUE TITLE
HW4 Grader Silently Failing Students

### ISSUE THREAD

**Issue by zhangaaron** [saasbook/rag#85]
Students receive 60/100, autograder does not tell them what failed. Possibly due to the fact that they have extra .feature files? 

Zip submission of a student that exhibits this problem: 
[hw4_bug0.zip](https://github.com/saasbook/rag/files/166355/hw4_bug0.zip)

**Comment by tansaku** [comment]
@zhangaaron maybe turn into a failing acceptance test and open a pull request?

**Comment by zhangaaron** [comment]
well i have a test that demonstrates failure, but doesn't actual check for it -- would have to parse the output of the autograder for that test rather than inspecting variables so a bit of overhead there. but that has been pushed to the 85_ branch. the problem has been narrowed down to rake task saas.rake failing when grading student cucumber and rspec tests. Unsure why, there is a rescue clause in there that should prevent it from happening but no exception is caught even though the rake task exits prematurely with status != 0 as well.

**Comment by zhangaaron** [comment]
I am having a hard time isolating this problem past the fact that ```       Rake::Task["cucumber"].invoke ``` seems to be buggy and causes the entire rake task to exit, even though there is a rescue clause around it. The cucumber test has 1 example failed in it, but when I run the rake cucumber task from terminal I actually can't replicate that example failure.

**Comment by tansaku** [comment]
I think I've fixed this by increasing the output to students
